package ch.interlis.generator.metadata.merge;

/**
 * Stabiler maschinenlesbarer Code eines Merge-Diagnostics.
 */
public enum MergeDiagnosticCode {
    MODEL_NAME_MISMATCH,
    CLASS_ONLY_IN_PHYSICAL,
    CLASS_ONLY_IN_SEMANTIC,
    ATTRIBUTE_UNMATCHED,
    ATTRIBUTE_AMBIGUOUS,
    ATTRIBUTE_PHYSICAL_REUSED,
    RELATIONSHIP_UNMATCHED,
    RELATIONSHIP_AMBIGUOUS,
    RELATIONSHIP_PHYSICAL_REUSED,
    ASSOCIATION_ROLE_UNRESOLVED,
    ASSOCIATION_ROLE_DUPLICATE,
    DUPLICATE_CANONICAL_RELATIONSHIP,
    MERGE_INVARIANT_VIOLATION
}
