package ch.interlis.generator.grails.verification.mapping;

/**
 * Codes für Mapping-Abweichungen (Spezifikation §34.1).
 */
public enum MappingMismatchCode {
    ENTITY_MISSING_IN_HIBERNATE,
    ENTITY_MISSING_IN_DATABASE,
    UNEXPECTED_HIBERNATE_ENTITY,
    TABLE_NAME_MISMATCH,
    ID_COLUMN_MISMATCH,
    VERSION_MAPPING_MISMATCH,
    PROPERTY_MISSING,
    COLUMN_NAME_MISMATCH,
    NULLABILITY_MISMATCH,
    RELATIONSHIP_TARGET_MISMATCH,
    FOREIGN_KEY_COLUMN_MISMATCH,
    FOREIGN_KEY_TARGET_MISMATCH,
    COLLECTION_MAPPING_MISMATCH,
    UNEXPECTED_JOIN_TABLE,
    ASSOCIATION_STORAGE_MISMATCH,
    GEOMETRY_TYPE_MISMATCH,
    GEOMETRY_SRID_MISMATCH
}
