package ch.interlis.generator.model;

/**
 * Codes der Modell-Validierung.
 */
public enum ModelMetadataDiagnosticCode {
    EMPTY_MODEL_NAME,
    DUPLICATE_CLASS,
    DUPLICATE_ATTRIBUTE,
    DUPLICATE_RELATIONSHIP_IDENTITY,
    DUPLICATE_PHYSICAL_TABLE,
    DUPLICATE_PHYSICAL_COLUMN,
    UNRESOLVED_SOURCE_CLASS,
    UNRESOLVED_TARGET_CLASS,
    UNRESOLVED_ASSOCIATION_ROLE_TARGET,
    UNRESOLVED_ENUM_TYPE,
    UNRESOLVED_TYPE,
    INCONSISTENT_GEOMETRY,
    NULL_COLLECTION_ENTRY,
    MUTABLE_COLLECTION
}
