package ch.interlis.generator.grails;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Test harness helper that makes the {@code ili2grails-runtime} plugin
 * available to temporary Grails apps generated by the smoke/contract tests.
 *
 * <p>The harness publishes the plugin (and the runtime API) to the local
 * Maven repository and injects the plugin dependency plus the {@code
 * mavenLocal()} repository into the app build file. This mirrors the final
 * consumer path; {@code mavenLocal()} is a test/development harness only.</p>
 */
final class RuntimeApiTestSupport {

    static final String RUNTIME_GROUP = "ch.interlis.generator";
    static final String RUNTIME_ARTIFACT = "ili2grails-runtime";
    static final String RUNTIME_VERSION = "1.0.0-SNAPSHOT";
    static final String RUNTIME_NOTATION =
        RUNTIME_GROUP + ":" + RUNTIME_ARTIFACT + ":" + RUNTIME_VERSION;

    static final String RUNTIME_DEPENDENCY_MARKER = "ili2grails-runtime";

    private RuntimeApiTestSupport() {
    }

    /** Publishes plugin + API to the local Maven repository. */
    static void publishRuntimeToMavenLocal(Path gradleDir) throws IOException, InterruptedException {
        List<String> command = new ArrayList<>(List.of(
            "./gradlew",
            ":grails-runtime:publishToMavenLocal",
            ":grails-runtime-api:publishToMavenLocal",
            "--no-daemon"
        ));
        Process process = new ProcessBuilder(command)
            .directory(gradleDir.toFile())
            .inheritIO()
            .start();
        int exitCode = process.waitFor();
        if (exitCode != 0) {
            throw new IOException(
                "publishToMavenLocal failed with exit code " + exitCode);
        }
    }

    static void installRuntimePluginDependency(Path appDir) throws IOException {
        ensureMavenLocalRepository(appDir.resolve("build.gradle"));
        new ch.interlis.generator.grails.project.GrailsRuntimeDependencyInstaller().install(
            appDir.resolve("build.gradle"),
            ch.interlis.generator.grails.project.RuntimeCoordinates.ili2grailsRuntime()
        );
        ensureChangingSnapshotResolution(appDir.resolve("build.gradle"));
    }

    /**
     * Re-resolve SNAPSHOT versions on every build so re-published harness
     * artifacts are picked up immediately (test/development harness only).
     */
    private static void ensureChangingSnapshotResolution(Path buildGradlePath) throws IOException {
        if (!Files.exists(buildGradlePath)) {
            return;
        }
        String marker = "// <ili2grails-snapshot-resolution>";
        String content = Files.readString(buildGradlePath, StandardCharsets.UTF_8);
        if (content.contains(marker)) {
            return;
        }
        String block = "\n" + marker + "\n"
            + "configurations.all {\n"
            + "    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'\n"
            + "}\n"
            + "// </ili2grails-snapshot-resolution>\n";
        Files.writeString(buildGradlePath, content + block, StandardCharsets.UTF_8);
    }

    private static void ensureMavenLocalRepository(Path buildGradlePath) throws IOException {
        if (!Files.exists(buildGradlePath)) {
            return;
        }
        List<String> lines = Files.readAllLines(buildGradlePath, StandardCharsets.UTF_8);
        List<String> updated = ensureMavenLocalRepository(lines);
        if (!updated.equals(lines)) {
            Files.write(buildGradlePath, updated, StandardCharsets.UTF_8);
        }
    }

    private static List<String> ensureMavenLocalRepository(List<String> lines) {
        List<String> updated = new ArrayList<>(lines);
        boolean present = lines.stream()
            .anyMatch(line -> line.trim().startsWith("mavenLocal()"));
        if (present) {
            return lines;
        }
        int[] buildscriptRange = findBlockRange(updated, "buildscript", null);
        int[] repositoriesRange = findBlockRange(updated, "repositories", buildscriptRange);
        if (repositoriesRange == null) {
            return lines;
        }
        String indent = detectIndent(updated, repositoriesRange[0]);
        updated.add(repositoriesRange[1], indent + "mavenLocal()");
        return updated;
    }

    private static int[] findBlockRange(List<String> lines, String blockName, int[] excludeRange) {
        int blockStart = -1;
        int braceDepth = 0;
        for (int i = 0; i < lines.size(); i++) {
            if (excludeRange != null && i >= excludeRange[0] && i <= excludeRange[1]) {
                continue;
            }
            String trimmed = lines.get(i).trim();
            if (blockStart < 0 && trimmed.startsWith(blockName)) {
                blockStart = i;
                braceDepth += countChar(lines.get(i), '{');
                braceDepth -= countChar(lines.get(i), '}');
                if (braceDepth == 0) {
                    blockStart = -1;
                }
                continue;
            }
            if (blockStart >= 0) {
                braceDepth += countChar(lines.get(i), '{');
                braceDepth -= countChar(lines.get(i), '}');
                if (braceDepth == 0) {
                    return new int[] { blockStart, i };
                }
            }
        }
        return null;
    }

    private static String detectIndent(List<String> lines, int blockStart) {
        for (int i = blockStart + 1; i < lines.size(); i++) {
            String line = lines.get(i);
            if (line.isBlank()) {
                continue;
            }
            int leadingSpaces = line.indexOf(line.trim());
            if (leadingSpaces > 0) {
                return line.substring(0, leadingSpaces);
            }
            if (line.trim().startsWith("}")) {
                break;
            }
        }
        return "    ";
    }

    private static int countChar(String line, char token) {
        int count = 0;
        for (int i = 0; i < line.length(); i++) {
            if (line.charAt(i) == token) {
                count++;
            }
        }
        return count;
    }
}
