package ch.interlis.generator.grails;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Comparator;
import java.util.List;

/**
 * Test harness helper that makes the built {@code grails-runtime-api} jar
 * available to temporary Grails apps generated by the smoke/contract tests.
 *
 * <p>Interim bridging step only: the final dependency injection path is the
 * runtime plugin coordinates (see {@code GrailsRuntimeDependencyInstaller}).
 * This helper is replaced by the plugin consumer tests once the plugin module
 * exists.</p>
 */
final class RuntimeApiTestSupport {

    private static final String API_CLASS = "ch/interlis/generator/grails/runtime/api/descriptor/DomainDescriptor.class";
    private static final String API_JAR_NAME = "grails-runtime-api.jar";
    private static final String API_JAR_MARKER = "grails-runtime-api.jar";

    private RuntimeApiTestSupport() {
    }

    static void installRuntimeApiJar(Path appDir) throws IOException {
        Path libsDir = appDir.resolve("libs");
        Files.createDirectories(libsDir);
        Path jarTarget = libsDir.resolve(API_JAR_NAME);

        Path apiJar = locateApiJar();
        if (apiJar != null) {
            Files.copy(apiJar, jarTarget, StandardCopyOption.REPLACE_EXISTING);
        } else {
            throw new IOException(
                "Could not locate grails-runtime-api jar on the test classpath");
        }

        new GrailsBuildGradleUpdater().ensureManagedDependency(
            appDir.resolve("build.gradle"),
            API_JAR_MARKER,
            "implementation files('libs/" + API_JAR_NAME + "')"
        );
    }

    private static Path locateApiJar() throws IOException {
        Path fromClasspath = locateApiJarOnClasspath();
        if (fromClasspath != null) {
            return fromClasspath;
        }
        Path moduleLibs = Path.of("grails-runtime-api", "build", "libs");
        if (Files.isDirectory(moduleLibs)) {
            try (var stream = Files.list(moduleLibs)) {
                List<Path> jars = stream
                    .filter(Files::isRegularFile)
                    .filter(path -> path.getFileName().toString().startsWith("grails-runtime-api-"))
                    .filter(path -> path.getFileName().toString().endsWith(".jar"))
                    .sorted(Comparator.comparingLong(path -> {
                        try {
                            return Files.getLastModifiedTime(path).toMillis();
                        } catch (IOException ignored) {
                            return 0L;
                        }
                    }))
                    .toList();
                if (!jars.isEmpty()) {
                    return jars.get(jars.size() - 1);
                }
            }
        }
        return null;
    }

    private static Path locateApiJarOnClasspath() {
        String classPath = System.getProperty("java.class.path");
        if (classPath == null) {
            return null;
        }
        for (String entry : classPath.split(System.getProperty("path.separator"))) {
            if (entry.contains("grails-runtime-api") && entry.endsWith(".jar")) {
                return Path.of(entry);
            }
        }
        return null;
    }
}
