package ch.interlis.generator.grails.runtime.registry

import ch.interlis.generator.grails.runtime.api.registry.AssociationRegistry
import ch.interlis.generator.grails.runtime.api.registry.DomainRegistry
import ch.interlis.generator.grails.runtime.api.registry.InterlisRuntimeRegistry
import ch.interlis.generator.grails.runtime.api.registry.RuntimeClassResolver
import org.springframework.beans.factory.FactoryBean

/**
 * Builds the {@link InterlisRuntimeRegistry} from the generated registry
 * classes of the host application.
 *
 * <p>The generated registries are static singletons in the fixed package
 * {@code ch.interlis.generator.grails.generated}; the plugin resolves them
 * once at startup and fails with a readable message when they are missing.</p>
 */
final class InterlisRuntimeRegistryBeanFactory implements FactoryBean<InterlisRuntimeRegistry> {

    static final String GENERATED_REGISTRY_PACKAGE = 'ch.interlis.generator.grails.generated'

    def grailsApplication

    private volatile InterlisRuntimeRegistry instance

    @Override
    InterlisRuntimeRegistry getObject() throws Exception {
        if (instance == null) {
            synchronized (this) {
                if (instance == null) {
                    instance = buildRegistry()
                }
            }
        }
        return instance
    }

    @Override
    Class<?> getObjectType() {
        return InterlisRuntimeRegistry
    }

    @Override
    boolean isSingleton() {
        return true
    }

    private InterlisRuntimeRegistry buildRegistry() {
        DomainRegistry domainRegistry = loadSingleton(DomainRegistry, 'InterlisUiRegistry')
        AssociationRegistry associationRegistry =
            loadSingleton(AssociationRegistry, 'InterlisAssociationRegistry')
        RuntimeClassResolver resolver = new GrailsRuntimeClassResolver(grailsApplication)
        return new InterlisRuntimeRegistry(domainRegistry, associationRegistry, resolver)
    }

    private static <T> T loadSingleton(Class<T> contract, String simpleName) {
        String qualifiedName = GENERATED_REGISTRY_PACKAGE + '.' + simpleName
        ClassLoader classLoader = InterlisRuntimeRegistryBeanFactory.classLoader
        try {
            Class<?> registryType = Class.forName(qualifiedName, true, classLoader)
            def instanceField = registryType.getDeclaredField('INSTANCE')
            instanceField.accessible = true
            Object instance = instanceField.get(null)
            if (instance == null) {
                throw new IllegalStateException(
                    "Generated registry ${qualifiedName} has no INSTANCE singleton")
            }
            if (!contract.isInstance(instance)) {
                throw new IllegalStateException(
                    "Generated registry ${qualifiedName} does not implement ${contract.name}")
            }
            return contract.cast(instance)
        } catch (ClassNotFoundException missing) {
            throw new IllegalStateException(
                "Generated registry ${qualifiedName} not found. " +
                "The application must be generated by the ili2grails generator.", missing)
        }
    }
}
