package ch.interlis.generator.grails.runtime

/**
 * Resolves the generated registry classes of the host application.
 *
 * <p>The generated registries live in the fixed package
 * {@code ch.interlis.generator.grails.generated} of the application, so the
 * plugin cannot reference them at compile time. Access happens through this
 * tiny indirection only; the typed contract is the API interfaces.</p>
 */
public final class GeneratedRegistryAccessor {

    private static final String GENERATED_PACKAGE = 'ch.interlis.generator.grails.generated'
    private static final ClassLoader CLASS_LOADER = GeneratedRegistryAccessor.classLoader

    private GeneratedRegistryAccessor() {
    }

    static Object uiRegistryInstance() {
        return instanceOf(load('InterlisUiRegistry'))
    }

    static Object associationRegistryInstance() {
        return instanceOf(load('InterlisAssociationRegistry'))
    }

    private static Class<?> load(String simpleName) {
        try {
            return Class.forName("${GENERATED_PACKAGE}.${simpleName}", true, CLASS_LOADER)
        } catch (ClassNotFoundException missing) {
            throw new IllegalStateException(
                "Generated registry ${GENERATED_PACKAGE}.${simpleName} not found on the classpath. " +
                "The application must be generated by the ili2grails generator.", missing)
        }
    }

    private static Object instanceOf(Class<?> registryType) {
        try {
            def instanceField = registryType.getDeclaredField('INSTANCE')
            instanceField.accessible = true
            Object instance = instanceField.get(null)
            if (instance == null) {
                throw new IllegalStateException(
                    "Generated registry ${registryType.name} has no INSTANCE singleton")
            }
            return instance
        } catch (NoSuchFieldException missingSingleton) {
            throw new IllegalStateException(
                "Generated registry ${registryType.name} has no INSTANCE singleton", missingSingleton)
        }
    }
}
