package ch.interlis.generator.grails.runtime.api.command;

/**
 * Typed result code of a runtime command.
 */
public enum CommandCode {
    CREATED,
    DELETED,
    ASSIGNED,
    REASSIGNED,
    ALREADY_ASSIGNED,
    READ_ONLY,
    FORBIDDEN,
    OWNER_NOT_FOUND,
    TARGET_NOT_FOUND,
    ASSOCIATION_NOT_FOUND,
    CONTEXT_INVALID,
    OWNERSHIP_MISMATCH,
    TARGET_ROLE_INVALID,
    DUPLICATE_LINK,
    CARDINALITY_MAX_EXCEEDED,
    CARDINALITY_MIN_VIOLATED,
    REASSIGNMENT_CONFIRMATION_REQUIRED,
    VALIDATION_FAILED,
    DATA_INTEGRITY,
    CONCURRENT_MODIFICATION,
    CONFIGURATION_INVALID,
    INTERNAL_ERROR,
    RELATIONSHIP_INVALID,
    TARGET_REQUIRED,
    COMPOSITION_DELETE_BLOCKED,
    EXTERNAL_DELETE_BLOCKED,
    RUNTIME_DESCRIPTOR_INVALID
}
