package ch.interlis.generator.testsupport;

import java.sql.Connection;
import java.sql.Statement;

/**
 * H2-ili2db-Fixture für MergeAmbiguityCases.
 */
public final class MergeAmbiguityFixtures {

    private MergeAmbiguityFixtures() {
    }

    /**
     * Legt die Metatabellen und Domain-Tabellen für MergeAmbiguityCases an.
     */
    public static void createMergeAmbiguityIli2dbFixture(Connection connection) throws Exception {
        try (Statement stmt = connection.createStatement()) {
            stmt.execute("CREATE TABLE t_ili2db_classname ("
                + "iliname VARCHAR(1024) PRIMARY KEY, sqlname VARCHAR(1024))");
            stmt.execute("CREATE TABLE t_ili2db_attrname ("
                + "iliname VARCHAR(1024), sqlname VARCHAR(1024), colowner VARCHAR(1024), target VARCHAR(1024))");
            stmt.execute("CREATE TABLE t_ili2db_settings ("
                + "tag VARCHAR(1024), setting VARCHAR(1024))");
            stmt.execute("CREATE TABLE t_ili2db_inheritance ("
                + "thisclass VARCHAR(1024), baseclass VARCHAR(1024))");
            stmt.execute("CREATE TABLE t_ili2db_column_prop ("
                + "tablename VARCHAR(255), columnname VARCHAR(255), tag VARCHAR(1024), setting VARCHAR(1024))");
            stmt.execute("CREATE TABLE t_ili2db_table_prop ("
                + "tablename VARCHAR(255), setting VARCHAR(255))");
            stmt.execute("CREATE TABLE t_ili2db_model ("
                + "modelname VARCHAR(1024), content VARCHAR(1024))");

            stmt.execute("INSERT INTO t_ili2db_classname VALUES "
                + "('MergeAmbiguityCases.Base.Owner', 'owner'), "
                + "('MergeAmbiguityCases.Base.Child', 'child'), "
                + "('MergeAmbiguityCases.Base.MismatchChild', 'mismatchchild'), "
                + "('MergeAmbiguityCases.Base.SameTargetAssoc', 'sametargetassoc')");

            stmt.execute("INSERT INTO t_ili2db_table_prop VALUES "
                + "('owner', 'CLASS'), "
                + "('child', 'CLASS'), "
                + "('mismatchchild', 'CLASS'), "
                + "('sametargetassoc', 'ASSOCIATION')");

            stmt.execute("INSERT INTO t_ili2db_attrname VALUES "
                + "('Name', 'name', 'MergeAmbiguityCases.Base.Owner', NULL), "
                + "('Name', 'name', 'MergeAmbiguityCases.Base.Child', NULL), "
                + "('OwnerRef', 'owner_id', 'MergeAmbiguityCases.Base.Child', 'MergeAmbiguityCases.Base.Owner'), "
                + "('Name', 'name', 'MergeAmbiguityCases.Base.MismatchChild', NULL), "
                + "('SemanticOwner', 'owner_fk', 'MergeAmbiguityCases.Base.MismatchChild', 'MergeAmbiguityCases.Base.Owner'), "
                + "('PrimaryOwner', 'primaryowner', 'MergeAmbiguityCases.Base.SameTargetAssoc', 'MergeAmbiguityCases.Base.Owner'), "
                + "('SecondaryOwner', 'secondaryowner', 'MergeAmbiguityCases.Base.SameTargetAssoc', 'MergeAmbiguityCases.Base.Owner')");

            stmt.execute("INSERT INTO t_ili2db_model VALUES "
                + "('MergeAmbiguityCases', 'MODEL')");

            stmt.execute("CREATE TABLE owner ("
                + "t_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "name VARCHAR(100))");
            stmt.execute("CREATE TABLE child ("
                + "t_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "name VARCHAR(100), owner_id INTEGER)");
            stmt.execute("CREATE TABLE mismatchchild ("
                + "t_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "name VARCHAR(100), owner_fk INTEGER)");
            stmt.execute("CREATE TABLE sametargetassoc ("
                + "t_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "primaryowner INTEGER, secondaryowner INTEGER)");
        }
    }
}
