package ch.interlis.generator.grails.runtime.api.registry;

/**
 * Codes for registry validation diagnostics.
 */
public enum RegistryDiagnosticCode {
    UNKNOWN_DOMAIN_CLASS,
    UNKNOWN_PROPERTY,
    UNKNOWN_RELATIONSHIP_TARGET,
    UNKNOWN_ASSOCIATION_DOMAIN_CLASS,
    UNKNOWN_ROLE_PROPERTY,
    UNKNOWN_CONTEXT_FIXED_PROPERTY,
    INCONSISTENT_EDITABLE_ROLES,
    UNKNOWN_INVERSE_RELATED_PROPERTY,
    UNKNOWN_GEOMETRY_FIELD,
    UNKNOWN_FILTER_FIELD,
    UNKNOWN_CONTROLLER,
    DUPLICATE_ID,
    DUPLICATE_NAME,
    UNRESOLVED_CONTEXT_ASSOCIATION,
    INVALID_CREATE_MODE,
    INVALID_STORAGE_KIND,
    VALIDATION_INCOMPLETE
}
